kotlin.stdlib.default.dependency=false
thePluginVersion=224.2.0
ideaSdkVersion=2024.3
riderSdkVersion=2024.3.0
riderProjectName=IntelligentComments.Rider
riderDll=IntelligentComments.Rider
commonDll=IntelligentComments
intellijPluginId=com.intelligentcomments
backendPluginId=IntelligentComments.Rider
buildConfiguration=Release
jvmVersion=17
theGradleVersion=8.11
vendor=AS