//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.11.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: RdComment.kt:12</p>
  /// </summary>
  public class RdCommentsSettingsModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<bool> EnableExperimentalFeatures => _EnableExperimentalFeatures;
    
    //private fields
    [NotNull] private readonly RdProperty<bool> _EnableExperimentalFeatures;
    
    //primary constructor
    private RdCommentsSettingsModel(
      [NotNull] RdProperty<bool> enableExperimentalFeatures
    )
    {
      if (enableExperimentalFeatures == null) throw new ArgumentNullException("enableExperimentalFeatures");
      
      _EnableExperimentalFeatures = enableExperimentalFeatures;
      _EnableExperimentalFeatures.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("enableExperimentalFeatures", _EnableExperimentalFeatures));
    }
    //secondary constructor
    internal RdCommentsSettingsModel (
    ) : this (
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 3658469664905839431L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RdCommentsSettingsModel (");
      using (printer.IndentCookie()) {
        printer.Print("enableExperimentalFeatures = "); _EnableExperimentalFeatures.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class ShellModelRdCommentsSettingsModelEx
   {
    public static RdCommentsSettingsModel GetRdCommentsSettingsModel(this ShellModel shellModel)
    {
      return shellModel.GetOrCreateExtension("rdCommentsSettingsModel", () => new RdCommentsSettingsModel());
    }
  }
}
